apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-org-demo
  description: An example deployment of a Backstage application on github orgs.
  annotations:
    github.com/project-slug: backstage-poc/demo
spec:
  type: service
  owner: baclstage-poc/nandhithakamal
  lifecycle: experimental
